config/routes.rb
Rails.application.routes.draw do
  root to: 'kittens#index'

  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def new
    @kitten = Kitten.new
  end

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render :json => @kittens}
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @kitten}
    end
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Kitten created"
      redirect_to @kitten
    else
      flash[:danger] = "Error"
      render :new
    end
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      flash[:success] = "Kitten updated"
      redirect_to @kitten
    else
      flash[:danger] = "Error"
      render :edit
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def destroy
    Kitten.find(params[:id]).destroy
    flash[:success] = "Kitten deleted"
    redirect_to root_path
  end

  private

    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for @kitten do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :age %>
    <%= f.text_field :age, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :cuteness %>
    <%= f.text_field :cuteness, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :softness %>
    <%= f.text_field :softness, class: 'form-control' %>
  </div>
  <%= link_to "Delete", kitten_path(@kitten.id), method: :delete,
      data: {confirm: 'Are you sure?'}, class: 'pull-right btn btn-danger' %>
  <%= f.submit yield(:button_text), class: 'btn btn-primary' %>
<% end %>

app/views/kittens/edit.html.erb
<% provide(:button_text, 'Update') %>
<h1>Edit Kitten</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/kittens/index.html.erb
<h1>Our Kittens</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% @kittens.each do |kit| %>
      <div class="well">
           <%= link_to kit.name, kitten_path(kit) %>
           <%= link_to "Delete", kitten_path(kit), method: :delete,
               data: {confirm: 'Are you sure?'}, class: 'pull-right' %>
      </div>
    <% end %>
  </div>
</div>

app/views/kittens/new.html.erb
<% provide(:button_text, 'Add') %>
<div class="row">
  <div class="col-md-6 col-offset-3">
    <h1>New Kitten</h1>
    <%= render 'form'%>
  </div>
</div>

app/views/kittens/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <ul class="list-unstyled well">
      <li>Name: <%= @kitten.name %></li>
      <li>Age: <%= @kitten.age %></li>
      <li>Softness: <%= @kitten.softness %></li>
      <li>Cuteness: <%= @kitten.cuteness %></li>
      <li> <%= link_to "Edit", edit_kitten_path(@kitten.id) %> </li>
      <li> <%= link_to "Delete", kitten_path(@kitten.id), method: :delete,
                                data: {confirm: 'Are you sure?'} %></li>
    </ul>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navlinks" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "KITTENS", root_url, class: "navbar-brand" %>
      </div>
    <div class="collapse navbar-collapse" id="navlinks">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Add Kitten', new_kitten_path %>  </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |type, mes| %>
      <div class="alert alert-<%= type %>">
        <%=mes %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>